name: "Build"

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu
          ## Lint all sources
          - os: ubuntu-24.04
            lint: true
          ## Debug + clang-tidy + coverage
          - os: ubuntu-24.04
            build_type: Debug
            sanitize: none
            coverage: true
            analyze: true
          ## Debug + sanitization
          - os: ubuntu-24.04
            build_type: Debug
            sanitize: address
          - os: ubuntu-24.04
            build_type: Debug
            sanitize: undefined
          - os: ubuntu-24.04
            build_type: Debug
            sanitize: thread
          ## Release
          - os: ubuntu-24.04
            build_type: Release
            sanitize: none
    runs-on: ${{ matrix.os }}
    env:
      JANK_MATRIX_ID: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.sanitize }}
      JANK_BUILD_TYPE: ${{ matrix.build_type }}
      JANK_LINT: ${{ matrix.lint }}
      JANK_COVERAGE: ${{ matrix.coverage }}
      JANK_ANALYZE: ${{ matrix.analyze }}
      JANK_SANITIZE: ${{ matrix.sanitize }}
      ASAN_OPTIONS: detect_leaks=0
      TERM: xterm
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and test
        run: |
          curl -sL -o install-bb https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install-bb
          sudo ./install-bb
          ./bin/jank/test_everything.clj
